apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-accounts
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  
  project: kafka    

  source:
    helm:
      version: v3
      valueFiles:
      - values-dev.yaml
    path: ./
    repoURL: https://github.com/paas2-rts/kowl.helm
    targetRevision: HEAD

  destination:
    namespace: kafka
    server: {{ .Values.spec.destination.server }}
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true   